service: sqlTool

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    BUCKET: ${env:BUCKET}

  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    path: ./.env
    basePath: ./
    logging: false

functions:
  run:
    handler: handler.run
    events:
      - http:
          path: run
          method: post
          cors: true

  read:
    handler: handler.tables
    events:
      - http:
          path: read
          method: get
          cors: true

  details:
    handler: handler.details
    events:
      - http:
          path: details
          method: get
          cors: true

  save:
    handler: handler.saveQuery
    events:
      - http:
          path: save
          method: post
          cors: true

  GetQueries:
    handler: handler.getQueries
    events:
      - http:
          path: save
          method: get
          cors: true
