service: sqlTool

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    path: ./.env
    basePath: ./
    logging: false

environment:
  DB_HOST: ${env:DB_HOST}
  DB_PORT: ${env:DB_PORT}
  DB_NAME: ${env:DB_NAME}
  DB_USERNAME: ${env:DB_USERNAME}
  DB_PASSWORD: ${env:DB_PASSWORD}

functions:
  run:
    handler: handler.run
    events:
      - http:
          path: run
          method: post

  read:
    handler: handler.tables
    events:
      - http:
          path: read
          method: get

  details:
    handler: handler.details
    events:
      - http:
          path: details
          method: get
